name: CI

on:
    push:
    pull_request:

env:
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_DB: test
    DATABASE_URL: postgresql+asyncpg://test:test@localhost:5432/test
    ENCRYPTION_KEY: TESTENCRYPTIONKEY
    EXPIRY_DURATION: 15
    ADMIN_EMAIL: admin.test@company.com
    ADMIN_PASSWORD: ADMIN1234

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Cache Poetry virtualenv
              uses: actions/cache@v5
              with:
                path: ~/.cache/pypoetry/virtualenvs
                key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

            - name: Install Dependencies
              run: |
                  pip install poetry --root-user-action=ignore
                  poetry install --with dev --no-root

            - name: Check Formatting
              run: poetry run ruff format --check .

            - name: Lint
              run: poetry run ruff check .

            - name: Test with pytest
              run: poetry run pytest -m unit


    integration-test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_USER: test
                    POSTGRES_PASSWORD: test
                    POSTGRES_DB: test
                ports:
                  - 5432:5432
                options: >-
                  --health-cmd pg_isready
                  --health-interval 10s
                  --health-timeout 5s
                  --health-retries 5
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Cache Poetry virtualenv
              uses: actions/cache@v5
              with:
                path: ~/.cache/pypoetry/virtualenvs
                key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

            - name: Install Dependencies
              run: |
                  pip install poetry --root-user-action=ignore
                  poetry install --with dev --no-root

            - name: Test with pytest
              run: poetry run pytest -m integration